{% set name = "priori" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ohsu-comp-bio/regulon-enrichment/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ed561810610d80524c3fdf51bbd1d087154b222452858e5ac54d4c9d8bb7a7bc

build:
  number: 0
  entry_points:
    - priori=priori

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - dill >=0.3.1.1
    - numpy >=1.17.3
    - pandas >=0.25.3
    - scikit-learn >=0.21.3
    - scipy >=1.5.2
    - tqdm >=4.38.0
    - statsmodels >=0.12.2

test:
  imports:
    - priori.priori
    - priori.data
    - priori.features
    - priori.regulon
  commands:
    - priori --help

about:
  home: https://github.com/ohsu-comp-bio/regulon-enrichment
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Priori predicts transcription factor activity from RNA sequencing data using prior, literature-supported regulatory relationship information

extra:
  recipe-maintainers:
    - yasharw
